# Generated by Django 5.1 on 2024-08-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountTransaction',
            new_name='Transaction',
        ),
    ]
