# Generated by Django 5.1 on 2024-08-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounttransaction_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='AccountTransaction',
        ),
    ]
