# Generated by Django 5.1 on 2024-08-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_transaction_accounttransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountTransaction',
        ),
    ]
