// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const LOGOUT = 'LOGOUT';

// Account
export const ACCOUNT_LOADED_SUCCESS = 'ACCOUNT_LOADED_SUCCESS';
export const ACCOUNT_LOADED_FAIL = 'ACCOUNT_LOADED_FAIL';
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_FAIL = 'ACCOUNT_CREATE_FAIL';
export const ACCOUNT_UPDATE_SUCCESS = 'ACCOUNT_UPDATE_SUCCESS';
export const ACCOUNT_UPDATE_FAIL = 'ACCOUNT_UPDATE_FAIL';
export const ACCOUNT_DELETE_SUCCESS = 'ACCOUNT_DELETE_SUCCESS';
export const ACCOUNT_DELETE_FAIL = 'ACCOUNT_DELETE_FAIL';

// Transaction
export const TRANSACTION_LOADED_SUCCESS = 'TRANSACTION_LOADED_SUCCESS';
export const TRANSACTION_LOADED_FAIL = 'TRANSACTION_LOADED_FAIL';
export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_CREATE_FAIL = 'TRANSACTION_CREATE_FAIL';
export const TRANSACTION_UPDATE_SUCCESS = 'TRANSACTION_UPDATE_SUCCESS';
export const TRANSACTION_UPDATE_FAIL = 'TRANSACTION_UPDATE_FAIL';
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS';
export const TRANSACTION_DELETE_FAIL = 'TRANSACTION_DELETE_FAIL';

// Person
export const PERSONS_LOADED_SUCCESS = 'PERSONS_LOADED_SUCCESS';
export const PERSONS_LOADED_FAIL = 'PERSONS_LOADED_FAIL';
export const PERSON_LOADED_SUCCESS = 'PERSON_LOADED_SUCCESS';
export const PERSON_LOADED_FAIL = 'PERSON_LOADED_FAIL';
export const PERSON_CREATED_SUCCESS = 'PERSON_CREATED_SUCCESS';
export const PERSON_CREATED_FAIL = 'PERSON_CREATED_FAIL';
export const PERSON_UPDATED_SUCCESS = 'PERSON_UPDATED_SUCCESS';
export const PERSON_UPDATED_FAIL = 'PERSON_UPDATED_FAIL';
export const PERSON_DELETED_SUCCESS = 'PERSON_DELETED_SUCCESS';
export const PERSON_DELETED_FAIL = 'PERSON_DELETED_FAIL';
