from django.db import models
from django.conf import settings

class Report(models.Model):
    """
    Represents a report generated by a user. The report can be of different types
    and contains JSON data.
    """
    REPORT_TYPE_CHOICES = [
        ('Monthly', 'Monthly'),
        ('Quarterly', 'Quarterly'),
        ('Annual', 'Annual'),
    ]
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    report_type = models.CharField(max_length=10, choices=REPORT_TYPE_CHOICES)
    date_created = models.DateTimeField(auto_now_add=True)
    data = models.JSONField()  # Assume the report data is stored as JSON
    
    def __str__(self):
        return f"{self.report_type} Report by {self.user.username} on {self.date_created.strftime('%Y-%m-%d %H:%M:%S')}"
