# Generated by Django 5.1 on 2024-08-28 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_person_user'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='person',
        ),
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.account'),
            preserve_default=False,
        ),
    ]
