# Generated by Django 5.1 on 2024-08-14 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_balance'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapproval',
            options={'verbose_name_plural': 'Loan Approvals'},
        ),
        migrations.AlterModelOptions(
            name='loanrepayment',
            options={'verbose_name_plural': 'Loan Repayments'},
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='applied_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='loanapproval',
            old_name='approval_date',
            new_name='approved_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='name',
        ),
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0.05, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loantype',
            name='type',
            field=models.CharField(choices=[('short_term', 'Short-Term'), ('long_term', 'Long-Term')], default=0.05, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loantype'),
        ),
        migrations.AlterField(
            model_name='loanapproval',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Interest rate in percentage', max_digits=5),
        ),
    ]
