# Generated by Django 5.1 on 2024-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_interest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('running', 'Running'), ('defaulted', 'Defaulted')], default='pending', editable=False, max_length=10),
        ),
    ]
