# Generated by Django 5.1 on 2024-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_alter_auditlog_options_alter_loan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="total_repayments",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
