# Generated by Django 5.1 on 2024-09-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="date",
            new_name="timestamp",
        ),
    ]
