# Generated by Django 5.1 on 2024-08-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_accounttransaction'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account'),
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='transaction_date',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
