# Generated by Django 5.1 on 2024-08-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactiontype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('loan', 'Loan'), ('withdraw', 'Withdraw')], max_length=10, unique=True),
        ),
    ]
