# Generated by Django 5.1 on 2024-08-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactiontype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit'), ('loan', 'Loan')], max_length=10, unique=True),
        ),
    ]
