// src/redux/types.js

export const PERSON_ACTIONS = {
    FETCH_PERSONS_REQUEST: 'FETCH_PERSONS_REQUEST',
    FETCH_PERSONS_SUCCESS: 'FETCH_PERSONS_SUCCESS',
    FETCH_PERSONS_FAILURE: 'FETCH_PERSONS_FAILURE',
    FETCH_PERSON_REQUEST: 'FETCH_PERSON_REQUEST',
    FETCH_PERSON_SUCCESS: 'FETCH_PERSON_SUCCESS',
    FETCH_PERSON_FAILURE: 'FETCH_PERSON_FAILURE',
    CREATE_PERSON_REQUEST: 'CREATE_PERSON_REQUEST',
    CREATE_PERSON_SUCCESS: 'CREATE_PERSON_SUCCESS',
    CREATE_PERSON_FAILURE: 'CREATE_PERSON_FAILURE',
    UPDATE_PERSON_REQUEST: 'UPDATE_PERSON_REQUEST',
    UPDATE_PERSON_SUCCESS: 'UPDATE_PERSON_SUCCESS',
    UPDATE_PERSON_FAILURE: 'UPDATE_PERSON_FAILURE',
    DELETE_PERSON_REQUEST: 'DELETE_PERSON_REQUEST',
    DELETE_PERSON_SUCCESS: 'DELETE_PERSON_SUCCESS',
    DELETE_PERSON_FAILURE: 'DELETE_PERSON_FAILURE',
  };
  
  export const ACCOUNT_ACTIONS = {
    FETCH_ACCOUNT_BALANCE_SUCCESS: 'FETCH_ACCOUNT_BALANCE_SUCCESS',
    FETCH_ACCOUNT_BALANCE_FAILURE: 'FETCH_ACCOUNT_BALANCE_FAILURE',
    FETCH_ACCOUNTS_REQUEST: 'FETCH_ACCOUNTS_REQUEST',
    FETCH_ACCOUNTS_SUCCESS: 'FETCH_ACCOUNTS_SUCCESS',
    FETCH_ACCOUNTS_FAILURE: 'FETCH_ACCOUNTS_FAILURE',
    FETCH_ACCOUNT_REQUEST: 'FETCH_ACCOUNT_REQUEST',
    FETCH_ACCOUNT_SUCCESS: 'FETCH_ACCOUNT_SUCCESS',
    FETCH_ACCOUNT_FAILURE: 'FETCH_ACCOUNT_FAILURE',
    CREATE_ACCOUNT_REQUEST: 'CREATE_ACCOUNT_REQUEST',
    CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
    CREATE_ACCOUNT_FAILURE: 'CREATE_ACCOUNT_FAILURE',
    UPDATE_ACCOUNT_REQUEST: 'UPDATE_ACCOUNT_REQUEST',
    UPDATE_ACCOUNT_SUCCESS: 'UPDATE_ACCOUNT_SUCCESS',
    UPDATE_ACCOUNT_FAILURE: 'UPDATE_ACCOUNT_FAILURE',
    DELETE_ACCOUNT_REQUEST: 'DELETE_ACCOUNT_REQUEST',
    DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
    DELETE_ACCOUNT_FAILURE: 'DELETE_ACCOUNT_FAILURE',
  };
  