// loanActionTypes.js
export const FETCH_LOAN_TYPES_REQUEST = 'FETCH_LOAN_TYPES_REQUEST';
export const FETCH_LOAN_TYPES_SUCCESS = 'FETCH_LOAN_TYPES_SUCCESS';
export const FETCH_LOAN_TYPES_FAILURE = 'FETCH_LOAN_TYPES_FAILURE';

export const FETCH_LOANS_REQUEST = 'FETCH_LOANS_REQUEST';
export const FETCH_LOANS_SUCCESS = 'FETCH_LOANS_SUCCESS';
export const FETCH_LOANS_FAILURE = 'FETCH_LOANS_FAILURE';

export const FETCH_LOAN_DETAILS_REQUEST = 'FETCH_LOAN_DETAILS_REQUEST';
export const FETCH_LOAN_DETAILS_SUCCESS = 'FETCH_LOAN_DETAILS_SUCCESS';
export const FETCH_LOAN_DETAILS_FAILURE = 'FETCH_LOAN_DETAILS_FAILURE';

export const CREATE_LOAN_REQUEST = 'CREATE_LOAN_REQUEST';
export const CREATE_LOAN_SUCCESS = 'CREATE_LOAN_SUCCESS';
export const CREATE_LOAN_FAILURE = 'CREATE_LOAN_FAILURE';

export const APPROVE_LOAN_REQUEST = 'APPROVE_LOAN_REQUEST';
export const APPROVE_LOAN_SUCCESS = 'APPROVE_LOAN_SUCCESS';
export const APPROVE_LOAN_FAILURE = 'APPROVE_LOAN_FAILURE';

export const CREATE_LOAN_REPAYMENT_REQUEST = 'CREATE_LOAN_REPAYMENT_REQUEST';
export const CREATE_LOAN_REPAYMENT_SUCCESS = 'CREATE_LOAN_REPAYMENT_SUCCESS';
export const CREATE_LOAN_REPAYMENT_FAILURE = 'CREATE_LOAN_REPAYMENT_FAILURE';
