// src/redux/types.js

export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAILURE = 'FETCH_TRANSACTIONS_FAILURE';

export const FETCH_TRANSACTION_TYPES_REQUEST = 'FETCH_TRANSACTION_TYPES_REQUEST';
export const FETCH_TRANSACTION_TYPES_SUCCESS = 'FETCH_TRANSACTION_TYPES_SUCCESS';
export const FETCH_TRANSACTION_TYPES_FAILURE = 'FETCH_TRANSACTION_TYPES_FAILURE';

export const FETCH_SINGLE_TRANSACTION_REQUEST = 'FETCH_SINGLE_TRANSACTION_REQUEST';
export const FETCH_SINGLE_TRANSACTION_SUCCESS = 'FETCH_SINGLE_TRANSACTION_SUCCESS';
export const FETCH_SINGLE_TRANSACTION_FAILURE = 'FETCH_SINGLE_TRANSACTION_FAILURE';

export const POST_TRANSACTION_REQUEST = 'POST_TRANSACTION_REQUEST';
export const POST_TRANSACTION_SUCCESS = 'POST_TRANSACTION_SUCCESS';
export const POST_TRANSACTION_FAILURE = 'POST_TRANSACTION_FAILURE';
